name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Copy files via SSH
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no"
        run: |
          rsync -avz --delete --exclude='.git' ./ server29@192.168.168.29:/var/www/html/hemant/
